#!/bin/bash

set -e

THISFILE="$(realpath $0)"
THISDIR="$(dirname $THISFILE)"

cd $THISDIR/..

assets="
static/ext/jquery-3.3.1/jquery-3.3.1.min.js
static/ext/semantic-ui-2.3.1/semantic.min.css
static/ext/semantic-ui-2.3.1/semantic.min.js
static/ext/semantic-ui-2.3.1/themes/default/assets/fonts/icons.eot
static/ext/semantic-ui-2.3.1/themes/default/assets/fonts/icons.svg
static/ext/semantic-ui-2.3.1/themes/default/assets/fonts/icons.ttf
static/ext/semantic-ui-2.3.1/themes/default/assets/fonts/icons.woff
static/ext/semantic-ui-2.3.1/themes/default/assets/fonts/icons.woff2
static/ext/logo.png
"

for asset in $assets; do
	if ! [ -f "$asset" ]; then
		echo "missing $asset" 1>&2; exit 1
	fi
done
